#!/usr/bin/env python3
#
"""Print QR-Code for WLAN through python-escpos"""
from escpos import printer
import click
import asyncio
import prniotlet


def wlanQR_prn(prn, ssid, security):
    prn.proxy.qr("WIFI:S:{0}:T:WPA:P:{1};;".format(ssid, security), size=12)


@click.command()
@click.option("--ssid", required=True)
@click.option("--security", required=True)
def print_data(ssid, security):
    """Print the specified data

    :param ssid: SSID of the WLAN
    :param security: Security of that WLAN
    """
    escpos_printer = prniotlet.PrnIOTlet()
    escpos_printer.proxy.hw("init")
    escpos_printer.proxy.set(align="center", bold=True, width=2, height=2)
    escpos_printer.proxy.block_text(ssid, columns=16)
    escpos_printer.proxy.print_and_feed(1)
    wlanQR_prn(escpos_printer, ssid, security)
    escpos_printer.proxy.print_and_feed()
    escpos_printer.proxy.set(align="center", bold=False, width=1, height=1)
    escpos_printer.proxy.text("Key:\n")
    escpos_printer.proxy.block_text(security, font='a', columns=16)
    escpos_printer.proxy.print_and_feed(4)
    escpos_printer.final_print()


if __name__ == "__main__":
    print_data()
