#! /usr/bin/env python3
# -*- coding: utf-8 -*-
# vim:fenc=utf-8
#
# Copyright © 2017 ch <christoph@heuel-web.de>
#
# Distributed under terms of the MIT license.

"""
aimoas print server
"""
from escpos import printer, config
import aiomas
import uuid
import time


class SessionException(Exception):
    """
    Exception Class showing another that an other session is active/in use
    """
    pass


class PrnIOLetSession(object):
    """
    Class for Session Objects
    """

    def __init__(self):
        self._session_string = uuid.uuid4().__str__()
        self._timestamp = time.time()

    def is_active(self):
        """
        Returns if a session is active. This means, that the delta is smaller
        than 180 secs
        """
        return ((time.time() - self._timestamp) <= 3*60)

    def is_same(self, session_id):
        """
        Compare session string with internal
        """
        return self._session_string == session_id

    def update(self):
        """
        Update timestamp
        """
        self._timestamp = time.time()

    def __str__(self):
        """
        Return Session String
        """
        return self._session_string


class ESCPOSServer(printer.Dummy):
    router = aiomas.rpc.Service()
    printer_real = config.Config().printer()
    active_session = None

    def __init__(self):
        super().__init__()

    @aiomas.expose
    def start_session(self):
        """
        Start a Session for the server. If a session is active, no other
        requests can be done
        """
        if not ESCPOSServer.active_session:
            ESCPOSServer.active_session = PrnIOLetSession()
            print("Starting Session ", ESCPOSServer.active_session)
            return ESCPOSServer.active_session
        elif not ESCPOSServer.active_session.is_active():
            print("Session expired ", ESCPOSServer.active_session)
            ESCPOSServer.active_session = PrnIOLetSession()
            print("Starting Session ", ESCPOSServer.active_session)
            return ESCPOSServer.active_session
        else:
            raise SessionException("Another Session is active")

    @aiomas.expose
    def close_session(self, session_id):
        """
        Close a existing session
        """
        if ESCPOSServer.active_session.is_same(session_id) or not ESCPOSServer.active_session.is_active():
            print("Closing Session ", ESCPOSServer.active_session)
            ESCPOSServer.active_session = None
            self._output_list.clear()
        else:
            print("Wrong Session:", session_id, "Active One:",
                  ESCPOSServer.active_session)
            raise SessionException("Wrong Session")

    @aiomas.expose
    def raw_data(self, session_id, msg):
        """
        Print raw data to the Dummy Device
        """
        if ESCPOSServer.active_session.is_same(session_id):
            print("Receiving Raw Data")
            super()._raw(msg)
            ESCPOSServer.active_session.update()
        else:
            print("Wrong Session:", session_id, "Active One:",
                  ESCPOSServer.active_session)
            raise SessionException("Wrong Session")

    @aiomas.expose
    def final_print(self, session_id):
        """
        Print to the actual server
        """
        if ESCPOSServer.active_session.is_same(session_id):
            print("Printing...")
            ESCPOSServer.printer_real._raw(self.output)
            self._output_list.clear()
            ESCPOSServer.active_session.update()
        else:
            print("Wrong Session:", session_id, "Active One:",
                  ESCPOSServer.active_session)
            raise SessionException("Wrong Session")


if __name__ == "__main__":
    server = aiomas.run(aiomas.rpc.start_server(('0.0.0.0', 5555),
                                                ESCPOSServer(),
                                                codec=aiomas.codecs.MsgPack))
    aiomas.run(server.wait_closed())
