#!/usr/bin/env python3
#
"""Print Text through python-escpos"""
from escpos import printer
import click
import asyncio
import prniotlet
from PIL import Image, ImageFont, ImageDraw

def print_graphic(prn, width, height, text):
    img = Image.new('RGB', (height, width), color = 'white')
    draw = ImageDraw.Draw(img)
    draw.multiline_text((0, 0), text, 
            font=ImageFont.truetype("arial", 26), 
            fill="black")
    prn.image(img)

@click.command()
@click.option("--height", required=False, default=272)
@click.option("--width", required=False, default=378)
@click.argument("text", required=True)
def print_data(height, width, text):
    """Print the specified data

    :param caption: Title
    :param text: Text to print
    """
    escpos_printer = prniotlet.PrnIOTlet()
    escpos_printer.proxy.hw("init")
    print_graphic(escpos_printer.proxy, height, width, text)

    escpos_printer.final_print()


if __name__ == "__main__":
    print_data()
