#!/usr/bin/env python3
#
"""Print Text through python-escpos"""
from escpos import printer
import click
import asyncio
import prniotlet


@click.command()
@click.option("--caption", required=False)
@click.option("--text", required=True)
def print_data(text, caption=None):
    """Print the specified data

    :param caption: Title
    :param text: Text to print
    """
    escpos_printer = prniotlet.PrnIOTlet()
    escpos_printer.proxy.hw("init")
    if caption:
        escpos_printer.proxy.set(align="center", bold=True, width=2, height=2)
        escpos_printer.proxy.block_text(caption, columns=16)
        escpos_printer.proxy.print_and_feed(1)
    escpos_printer.proxy.print_and_feed()
    escpos_printer.proxy.set(align="center", bold=False, width=1, height=1)
    escpos_printer.proxy.block_text(text, font='a', columns=16)
    escpos_printer.proxy.print_and_feed(4)
    escpos_printer.final_print()


if __name__ == "__main__":
    print_data()
