#!/usr/bin/env python3
#
"""Print QR-Code for WLAN through python-escpos"""
from escpos import printer
import click
import aiomas
import asyncio


def wlanQR_prn(prn, ssid, security):
    prn.qr("WIFI:S:{0}:T:WPA:P:{1};;".format(ssid, security), size=12)

@asyncio.coroutine
def _final_print(data):
    rpc_con = yield from aiomas.rpc.open_connection(('raspberrypi', 5555), codec=aiomas.MsgPack)
    try:
        session = yield from rpc_con.remote.start_session()
        yield from rpc_con.remote.raw_data(session, data)
        yield from rpc_con.remote.final_print(session)
    except Exception as e:
        print("Error occurred!", e)
    finally:
        yield from rpc_con.remote.close_session(session)
        yield from rpc_con.close()


@click.command()
@click.option("--ssid", required=True)
@click.option("--security", required=True)
def print_data(ssid, security):
    """Print the specified data

    :param ssid: SSID of the WLAN
    :param security: Security of that WLAN
    """
    escpos_printer = printer.Dummy()
    escpos_printer.hw("init")
    escpos_printer.set(align="center", bold=True, width=2, height=2)
    escpos_printer.block_text(ssid, columns=16)
    escpos_printer.print_and_feed(1)
    wlanQR_prn(escpos_printer, ssid, security)
    escpos_printer.print_and_feed()
    escpos_printer.set(align="center", bold=False, width=1, height=1)
    escpos_printer.text("Key:\n")
    escpos_printer.block_text(security, font='a', columns=16)
    escpos_printer.print_and_feed(4)
    aiomas.run(_final_print(escpos_printer.output))


if __name__ == "__main__":
    print_data()
